image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_CURRENT_DEV_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME-dev-$CI_BUILD_REF
  CONTAINER_CURRENT_DEV_ARMV7_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME-dev-armv7-$CI_BUILD_REF
  CONTAINER_LATEST_DEV_IMAGE: $CI_REGISTRY_IMAGE:dev-latest
  CONTAINER_LATEST_DEV_ARMV7_IMAGE: $CI_REGISTRY_IMAGE:dev-armv7-latest
  CONTAINER_CURRENT_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME-$CI_BUILD_REF
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME-latest

## DOCKER DEV BUILD

manual_build_dockerdev:
  stage: build
  except:
    - master
    - production
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_CURRENT_DEV_IMAGE -f Dockerfile.dev .
    - docker push $CONTAINER_CURRENT_DEV_IMAGE
  when: manual
  allow_failure: true

manual_build_dockerdev_latest:
  stage: build
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_CURRENT_DEV_IMAGE -f Dockerfile.dev .
    - docker tag $CONTAINER_CURRENT_DEV_IMAGE $CONTAINER_LATEST_DEV_IMAGE
    - docker push $CONTAINER_CURRENT_DEV_IMAGE
    - docker push $CONTAINER_LATEST_DEV_IMAGE
  when: manual
  allow_failure: true

manual_build_armv7_dockerdev:
  stage: build
  except:
    - master
    - production
  script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_CURRENT_DEV_ARMV7_IMAGE -f Dockerfile.armv7 .
    - docker push $CONTAINER_CURRENT_DEV_ARMV7_IMAGE
  when: manual
  allow_failure: true

manual_build_armv7_dockerdev_latest:
  stage: build
  only:
    - master
  script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_CURRENT_DEV_ARMV7_IMAGE -f Dockerfile.armv7 .
    - docker tag $CONTAINER_CURRENT_DEV_ARMV7_IMAGE $CONTAINER_LATEST_DEV_ARMV7_IMAGE
    - docker push $CONTAINER_CURRENT_DEV_ARMV7_IMAGE
    - docker push $CONTAINER_LATEST_DEV_ARMV7_IMAGE
  when: manual
  allow_failure: true
