FROM alpine:3.4
MAINTAINER Sraleik <sraleik@gmail.com>

RUN apk add --update nodejs bash alsa-utils sox && \
    rm -rf /var/cache/apk/*

RUN npm install -g nodemon

WORKDIR /app

EXPOSE 8080

CMD ["npm", "start" ]
